cmr_fup$peak_systolic_strain_rate_radial_1_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_3_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_6_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_9_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_12_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_15_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_1_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_3_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_5_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_7_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_9_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_11_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_13_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_15_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_1_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_3_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_5_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_7_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_9_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_11_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_13_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_15_fup.1 <- NULL
cmr_fup$peak_displacement_radial_2_fup.1 <- NULL
cmr_fup$peak_displacement_radial_6_fup.1 <- NULL
cmr_fup$peak_displacement_radial_10_fup.1 <- NULL
cmr_fup$peak_displacement_radial_13_fup.1 <- NULL
cmr_fup$peak_displacement_radial_16_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_3_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_6_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_9_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_12_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_15_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_2_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_5_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_8_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_11_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_14_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_1_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_4_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_7_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_10_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_13_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_16_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_2_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_4_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_6_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_8_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_10_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_12_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_14_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_16_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_2_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_4_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_6_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_8_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_10_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_12_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_14_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_16_fup.1. <- NULL
cmr_fup$peak_systolic_strain_rate_radial_2_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_4_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_7_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_10_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_13_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_16_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_2_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_4_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_6_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_8_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_10_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_12_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_14_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_circumferential_16_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_2_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_4_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_6_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_8_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_10_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_12_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_14_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_longitudinal_16_fup.1 <- NULL
cmr_fup$peak_displacement_radial_3_fup.1 <- NULL
cmr_fup$peak_displacement_radial_7_fup.1 <- NULL
cmr_fup$peak_displacement_radial_11_fup.1 <- NULL
cmr_fup$peak_displacement_radial_14_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_1_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_4_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_7_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_10_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_13_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_16_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_3_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_6_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_9_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_12_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_15_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_2_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_5_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_8_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_11_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_14_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_1_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_3_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_5_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_7_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_9_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_11_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_13_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_circumferential_15_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_1_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_3_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_5_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_7_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_9_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_11_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_13_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_15_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_5_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_8_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_11_fup.1 <- NULL
cmr_fup$peak_systolic_strain_rate_radial_14_fup.1 <- NULL
cmr_fup$peak_displacement_radial_1_fup.1 <- NULL
cmr_fup$peak_displacement_radial_4_fup.1 <- NULL
cmr_fup$peak_displacement_radial_8_fup.1 <- NULL
cmr_fup$peak_displacement_radial_12_fup.1 <- NULL
cmr_fup$peak_displacement_radial_15_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_2_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_5_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_8_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_11_fup.1 <- NULL
cmr_fup$peak_displacement_circumferential_14_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_1_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_4_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_7_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_10_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_13_fup.1 <- NULL
cmr_fup$peak_displacement_longitudinal_16_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_3_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_6_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_9_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_12_fup.1 <- NULL
cmr_fup$peak_systolic_velocity_radial_15_fup.1 <- NULL
cmr_fup$peak_displacement_radial_5_fup.1 <- NULL
cmr_fup$peak_displacement_radial_9_fup.1 <- NULL
cmr_fup$peak_displacement_radial_9_fup.1 <- NULL
cmr_fup$peak_displacement_radial_1_fup <- NULL
cmr_fup$peak_displacement_radial_3_fup <- NULL
cmr_fup$peak_displacement_radial_7_fup <- NULL
cmr_fup$peak_displacement_radial_10_fup <- NULL
cmr_fup$peak_displacement_radial_13_fup <- NULL
cmr_fup$peak_displacement_radial_16_fup <- NULL
cmr_fup$peak_displacement_circumferential_3_fup <- NULL
cmr_fup$peak_displacement_circumferential_6_fup <- NULL
cmr_fup$peak_displacement_circumferential_9_fup <- NULL
cmr_fup$peak_displacement_circumferential_12_fup <- NULL
cmr_fup$peak_displacement_circumferential_15_fup <- NULL
cmr_fup$peak_displacement_longitudinal_2_fup <- NULL
cmr_fup$peak_displacement_longitudinal_5_fup <- NULL
cmr_fup$peak_displacement_longitudinal_8_fup <- NULL
cmr_fup$peak_displacement_longitudinal_11_fup <- NULL
cmr_fup$peak_displacement_longitudinal_14_fup <- NULL
cmr_fup$peak_systolic_velocity_longitudinal_16_fup.1 <- NULL
cmr_fup$peak_displacement_radial_2_fup <- NULL
cmr_fup$peak_displacement_radial_4_fup <- NULL
cmr_fup$peak_displacement_radial_8_fup <- NULL
cmr_fup$peak_displacement_radial_11_fup <- NULL
cmr_fup$peak_displacement_radial_14_fup <- NULL
cmr_fup$peak_displacement_circumferential_1_fup <- NULL
cmr_fup$peak_displacement_circumferential_4_fup <- NULL
cmr_fup$peak_displacement_circumferential_7_fup <- NULL
cmr_fup$peak_displacement_circumferential_10_fup <- NULL
cmr_fup$peak_displacement_circumferential_13_fup <- NULL
cmr_fup$peak_displacement_circumferential_16_fup <- NULL
cmr_fup$peak_displacement_longitudinal_3_fup <- NULL
cmr_fup$peak_displacement_longitudinal_6_fup <- NULL
cmr_fup$peak_displacement_longitudinal_9_fup <- NULL
cmr_fup$peak_displacement_longitudinal_12_fup <- NULL
cmr_fup$peak_displacement_longitudinal_15_fup <- NULL
cmr_fup$peak_displacement_radial_5_fup <- NULL
cmr_fup$peak_displacement_radial_9_fup <- NULL
cmr_fup$peak_displacement_radial_12_fup <- NULL
cmr_fup$peak_displacement_radial_15_fup <- NULL
cmr_fup$peak_displacement_circumferential_2_fup <- NULL
cmr_fup$peak_displacement_circumferential_5_fup <- NULL
cmr_fup$peak_displacement_circumferential_8_fup <- NULL
cmr_fup$peak_displacement_circumferential_11_fup <- NULL
cmr_fup$peak_displacement_circumferential_14_fup <- NULL
cmr_fup$peak_displacement_longitudinal_1_fup <- NULL
cmr_fup$peak_displacement_longitudinal_4_fup <- NULL
cmr_fup$peak_displacement_longitudinal_7_fup <- NULL
cmr_fup$peak_displacement_longitudinal_10_fup <- NULL
cmr_fup$peak_displacement_longitudinal_13_fup <- NULL
cmr_fup$peak_displacement_longitudinal_16_fup <- NULL
cmr_fup$peak_displacement_radial_6_fup <- NULL