toredcap$...1212 <- NULL
toredcap$total_forward_volume_ao_cmr <- NULL
toredcap$total_backward_volume_ao_cmr <- NULL
toredcap$total_volume_ao_cmr <- NULL
toredcap$regurgitation_fraction_ao_cmr <- NULL
toredcap$vol_min_ao_cmr <- NULL
toredcap$max_pressure_gradient_ao_cmr <- NULL
toredcap$mean_pressure_gradient_ao_cmr <- NULL
toredcap$maximum_velocity_ao_cmr <- NULL
toredcap$total_forward_volume_pa_cmr <- NULL
toredcap$total_backward_volume_pa_cmr <- NULL
toredcap$total_volume_pa_cmr <- NULL
toredcap$regurgitation_fraction_pa_cmr <- NULL
toredcap$vol_min_pa_cmr <- NULL
toredcap$max_pressure_gradient_pa_cmr <- NULL
toredcap$mean_pressure_gradient_pa_cmr <- NULL
toredcap$maximum_velocity_pa_cmr <- NULL
toredcap$qp_qs_cmr <- NULL
toredcap$peak_diastolic_strain_rate_radial_1 <- NULL
toredcap$peak_diastolic_strain_rate_radial_2 <- NULL
toredcap$peak_diastolic_strain_rate_radial_3 <- NULL
toredcap$peak_diastolic_strain_rate_radial_4 <- NULL
toredcap$peak_diastolic_strain_rate_radial_5 <- NULL
toredcap$peak_diastolic_strain_rate_radial_6 <- NULL
toredcap$peak_diastolic_strain_rate_radial_7 <- NULL
toredcap$peak_diastolic_strain_rate_radial_8 <- NULL
toredcap$peak_diastolic_strain_rate_radial_9 <- NULL
toredcap$peak_diastolic_strain_rate_radial_10 <- NULL
toredcap$peak_diastolic_strain_rate_radial_11 <- NULL
toredcap$peak_diastolic_strain_rate_radial_12 <- NULL
toredcap$peak_diastolic_strain_rate_radial_13 <- NULL
toredcap$peak_diastolic_strain_rate_radial_14 <- NULL
toredcap$peak_diastolic_strain_rate_radial_15 <- NULL
toredcap$peak_diastolic_strain_rate_radial_16 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_1 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_2 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_3 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_4 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_5 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_6 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_7 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_8 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_9 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_10 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_11 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_12 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_13 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_14 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_15 <- NULL
toredcap$peak_diastolic_strain_rate_circumferential_16 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_1 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_2 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_3 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_4 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_5 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_6 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_7 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_8 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_9 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_10 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_11 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_12 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_13 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_14 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_15 <- NULL
toredcap$peak_diastolic_strain_rate_longitudinal_16 <- NULL
toredcap$peak_displacement_radial_1 <- NULL
toredcap$peak_displacement_radial_2 <- NULL
toredcap$peak_displacement_radial_3 <- NULL
toredcap$peak_displacement_radial_4 <- NULL
toredcap$peak_displacement_radial_5 <- NULL
toredcap$peak_displacement_radial_6 <- NULL
toredcap$peak_displacement_radial_7 <- NULL
toredcap$peak_displacement_radial_8 <- NULL
toredcap$peak_displacement_radial_9 <- NULL
toredcap$peak_displacement_radial_10 <- NULL
toredcap$peak_displacement_radial_11 <- NULL
toredcap$peak_displacement_radial_12 <- NULL
toredcap$peak_displacement_radial_13 <- NULL
toredcap$peak_displacement_radial_14 <- NULL
toredcap$peak_displacement_radial_15 <- NULL
toredcap$peak_displacement_radial_16 <- NULL
toredcap$peak_displacement_circumferential_1 <- NULL
toredcap$peak_displacement_circumferential_2 <- NULL
toredcap$peak_displacement_circumferential_3 <- NULL
toredcap$peak_displacement_circumferential_4 <- NULL
toredcap$peak_displacement_circumferential_5 <- NULL
toredcap$peak_displacement_circumferential_6 <- NULL
toredcap$peak_displacement_circumferential_7 <- NULL
toredcap$peak_displacement_circumferential_8 <- NULL
toredcap$peak_displacement_circumferential_9 <- NULL
toredcap$peak_displacement_circumferential_10 <- NULL
toredcap$peak_displacement_circumferential_11 <- NULL
toredcap$peak_displacement_circumferential_12 <- NULL
toredcap$peak_displacement_circumferential_13 <- NULL
toredcap$peak_displacement_circumferential_14 <- NULL
toredcap$peak_displacement_circumferential_15 <- NULL
toredcap$peak_displacement_circumferential_16 <- NULL
toredcap$peak_displacement_longitudinal_1 <- NULL
toredcap$peak_displacement_longitudinal_2 <- NULL
toredcap$peak_displacement_longitudinal_3 <- NULL
toredcap$peak_displacement_longitudinal_4 <- NULL
toredcap$peak_displacement_longitudinal_5 <- NULL
toredcap$peak_displacement_longitudinal_6 <- NULL
toredcap$peak_displacement_longitudinal_7 <- NULL
toredcap$peak_displacement_longitudinal_8 <- NULL
toredcap$peak_displacement_longitudinal_9 <- NULL
toredcap$peak_displacement_longitudinal_10 <- NULL
toredcap$peak_displacement_longitudinal_11 <- NULL
toredcap$peak_displacement_longitudinal_12 <- NULL
toredcap$peak_displacement_longitudinal_13 <- NULL
toredcap$peak_displacement_longitudinal_14 <- NULL
toredcap$peak_displacement_longitudinal_15 <- NULL
toredcap$peak_displacement_longitudinal_16 <- NULL
toredcap$peak_diastolic_velocity_radial_1 <- NULL
toredcap$peak_diastolic_velocity_radial_2 <- NULL
toredcap$peak_diastolic_velocity_radial_3 <- NULL
toredcap$peak_diastolic_velocity_radial_4 <- NULL
toredcap$peak_diastolic_velocity_radial_5 <- NULL
toredcap$peak_diastolic_velocity_radial_6 <- NULL
toredcap$peak_diastolic_velocity_radial_7 <- NULL
toredcap$peak_diastolic_velocity_radial_8 <- NULL
toredcap$peak_diastolic_velocity_radial_9 <- NULL
toredcap$peak_diastolic_velocity_radial_10 <- NULL
toredcap$peak_diastolic_velocity_radial_11 <- NULL
toredcap$peak_diastolic_velocity_radial_12 <- NULL
toredcap$peak_diastolic_velocity_radial_13 <- NULL
toredcap$peak_diastolic_velocity_radial_14 <- NULL
toredcap$peak_diastolic_velocity_radial_15 <- NULL
toredcap$peak_diastolic_velocity_radial_16 <- NULL
toredcap$peak_diastolic_velocity_circumferential_1 <- NULL
toredcap$peak_diastolic_velocity_circumferential_2 <- NULL
toredcap$peak_diastolic_velocity_circumferential_3 <- NULL
toredcap$peak_diastolic_velocity_circumferential_4 <- NULL
toredcap$peak_diastolic_velocity_circumferential_5 <- NULL
toredcap$peak_diastolic_velocity_circumferential_6 <- NULL
toredcap$peak_diastolic_velocity_circumferential_7 <- NULL
toredcap$peak_diastolic_velocity_circumferential_8 <- NULL
toredcap$peak_diastolic_velocity_circumferential_9 <- NULL
toredcap$peak_diastolic_velocity_circumferential_10 <- NULL
toredcap$peak_diastolic_velocity_circumferential_11 <- NULL
toredcap$peak_diastolic_velocity_circumferential_12 <- NULL
toredcap$peak_diastolic_velocity_circumferential_13 <- NULL
toredcap$peak_diastolic_velocity_circumferential_14 <- NULL
toredcap$peak_diastolic_velocity_circumferential_15 <- NULL
toredcap$peak_diastolic_velocity_circumferential_16 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_1 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_2 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_3 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_4 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_5 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_6 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_7 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_8 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_9 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_10 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_11 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_12 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_13 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_14 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_15 <- NULL
toredcap$peak_diastolic_velocity_longitudinal_16 <- NULL